name: Demo-app
on: push
jobs:
  Demo:
    runs-on: ubuntu-24.04
    steps:
      - name: Get Code from Repo
        uses: actions/checkout@v5
      - name: Install NodeJS
        uses: actions/setup-node@v3
       with:
        node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
  
