name: Demo-app
on: push
jobs:
  Demo:
    runs-on: ubuntu-24.04
    steps:
      - name: Get Code from Repo
        uses: actions/checkout@v5
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
