name: Demo-app
on: push
jobs:
  Demo:
    runs-on: ubuntu-24.04
    steps:
      - name: Get Code from Repo
        uses: actions/checkout@v7
      - name: Display Success
        run: echo "Display Success"
  
